spring:
  application:
    name: events
  jpa:
    generate-ddl: "false"
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        session_factory:
          statement_inspector: gae.piaz.logical.delete.config.CompositeInspector
        jdbc:
          time_zone: UTC
        format_sql: true

logging:
  level:
    gae.piaz: TRACE